# Generated by Django 3.1.1 on 2020-10-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
